# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
zh:
  languageCode: zh-Hans
  title: "Link 的博客"
  params:
    description: "Link 的个人博客网站"

# English as secondary language
# en:
#   languageCode: en-us
#   contentDir: content/en
#   title: "Link's Blog"
#   params:
#     description: "Link's personal blog website"
