# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: 首页
    url: /
    weight: 10
  - name: 博客
    url: blog/
    weight: 15
  - name: 标签
    url: tags/
    weight: 20
  - name: 工具
    url: uses/
    weight: 30
